CREATE TABLE "igrejas" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"codigo_totvs" varchar(100) NOT NULL,
	"desc_igreja" varchar(255) NOT NULL,
	"tipo_imovel" varchar(100),
	"endereco" varchar(255),
	"bairro" varchar(100),
	"municipio" varchar(100),
	"estado" varchar(2),
	"cep" varchar(20),
	"link_google_maps" varchar(500),
	"latitude" double precision,
	"longitude" double precision,
	"status" varchar(50) DEFAULT 'PENDENTE',
	"usuario_validador" varchar(255),
	"observacoes" varchar(1000),
	"porte" varchar(50),
	"codigo_totvs_pai" varchar(100),
	"validado_por" varchar(255),
	"validado_em" varchar(100),
	"dirigente_nome" varchar(255),
	"dirigente_telefone" varchar(50),
	"dirigente_email" varchar(255),
	"dirigente_data_posse" date,
	"financeira_nome" varchar(255),
	"financeira_telefone" varchar(50),
	"financeira_email" varchar(255),
	"qtd_membros" integer,
	"qtd_jovens" integer,
	"tipo_prebenda" varchar(50),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "igrejas_codigo_totvs_unique" UNIQUE("codigo_totvs")
);
