import { pgTable, uuid, varchar, doublePrecision, date, integer, timestamp } from 'drizzle-orm/pg-core';

export const igrejas = pgTable('igrejas', {
  id: uuid('id').defaultRandom().primaryKey(),
  codigo_totvs: varchar('codigo_totvs', { length: 100 }).notNull().unique(),
  desc_igreja: varchar('desc_igreja', { length: 255 }).notNull(),
  tipo_imovel: varchar('tipo_imovel', { length: 100 }),
  endereco: varchar('endereco', { length: 255 }),
  bairro: varchar('bairro', { length: 100 }),
  municipio: varchar('municipio', { length: 100 }),
  estado: varchar('estado', { length: 2 }),
  cep: varchar('cep', { length: 20 }),
  link_google_maps: varchar('link_google_maps', { length: 500 }),
  latitude: doublePrecision('latitude'),
  longitude: doublePrecision('longitude'),
  status: varchar('status', { length: 50 }).default('PENDENTE'),
  usuario_validador: varchar('usuario_validador', { length: 255 }),
  observacoes: varchar('observacoes', { length: 1000 }),
  porte: varchar('porte', { length: 50 }),
  codigo_totvs_pai: varchar('codigo_totvs_pai', { length: 100 }),
  validado_por: varchar('validado_por', { length: 255 }),
  validado_em: varchar('validado_em', { length: 100 }),
  dirigente_nome: varchar('dirigente_nome', { length: 255 }),
  dirigente_telefone: varchar('dirigente_telefone', { length: 50 }),
  dirigente_email: varchar('dirigente_email', { length: 255 }),
  dirigente_data_posse: date('dirigente_data_posse'),
  financeira_nome: varchar('financeira_nome', { length: 255 }),
  financeira_telefone: varchar('financeira_telefone', { length: 50 }),
  financeira_email: varchar('financeira_email', { length: 255 }),
  qtd_membros: integer('qtd_membros'),
  qtd_jovens: integer('qtd_jovens'),
  tipo_prebenda: varchar('tipo_prebenda', { length: 50 }),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});
